CREATE TABLE CONTACTPOINT(
	ID INT NOT NULL AUTO_INCREMENT,
	PATIENT_ID INT NOT NULL,
	SISTEMA VARCHAR(20),
	VALUE VARCHAR(20),
	USO VARCHAR(10),
	PRIMARY KEY (ID),
    FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(ID)
);