CREATE TABLE IDENTIFIER(
    ID INT NOT NULL AUTO_INCREMENT,
    PATIENT_ID INT NOT NULL,
    TIPO VARCHAR(20),
    VALUE VARCHAR(15),
    PRIMARY KEY (ID),
    FOREIGN KEY (PATIENT_ID) REFERENCES PATIENT(ID)
);